[pytest]
# https://pytest-django.readthedocs.io/en/latest/configuring_django.html
DJANGO_SETTINGS_MODULE = triplanner.settings
django_debug_mode = false

# Fail tests that render templates which make use of invalid template variables.
FAIL_INVALID_TEMPLATE_VARS = True
addopts =
    --no-migrations
    --cov-config=pytest.ini
    --cov-report=html:coverage/htmlcov

python_files = tests.py test_*.py *_tests.py

# https://pytest-cov.readthedocs.io/en/latest/config.html
# https://coverage.readthedocs.io/en/latest/config.html
[coverage:run]
branch = true
source_dirs =
    nucleo
    triplanner
omit =
    .venv/*
    coverage/*
    build/*
    **/migrations/*
    **/tests/*

[coverage:report]
show_missing = true
