# Generated by Django 6.0.4 on 2026-04-30 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('slug', models.SlugField(help_text='Nome limpo para urls e paths', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Nome da cidade', max_length=255)),
                ('importance', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], db_default=5, default=5, verbose_name='Importancia padrão')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, help_text='custo (em R$) para ir de origem a destino', max_digits=12, verbose_name='custo')),
                ('time', models.DurationField(help_text='Tempo (em Horas) de viagem de origem a destino', verbose_name='tempo')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='nucleo.city', verbose_name='destino')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nucleo.city', verbose_name='origem')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='routes',
            field=models.ManyToManyField(related_name='+', through='nucleo.Route', through_fields=('src', 'dest'), to='nucleo.city'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('src', 'dest'), name='unique_route'),
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('src', models.F('dest')), _negated=True), name='src_not_equal_dest', violation_error_message='Origem não pode ser igual a destino'),
        ),
    ]
